title = "PseudoPhysical"
baseURL = ""
languageCode = "en-us"
theme = "gohugo-theme-ananke"
themesDir = "./themes/"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-66251714-2"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "This sites design for me to post and share my experience while I explore and discovery the pseudo physical of me."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/jackteoh"
  linkedin = "https://www.linkedin.com/in/jackteoh/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/sunrise.jpg"
  recent_posts_number = 5
